project_name: auroraops
release:
  github:
    owner: ngerakines
    name: auroraops
  draft: true
build:
  binary: auroraops
  main: ./cmd/auroraops
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - 386
  ignore:
    - goos: openbsd
      goarch: arm
      goarm: 6
  env:
    - CGO_ENABLED=0
archive:
  name_template: "{{.Binary}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  replacements:
    amd64: 64bit
    386: 32bit
    arm: ARM
    arm64: ARM64
    darwin: macOS
    linux: Linux
    windows: Windows
    openbsd: OpenBSD
    netbsd: NetBSD
    freebsd: FreeBSD
    dragonfly: DragonFlyBSD
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
  - LICENSE.md
  - README.md
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
